"""Public API data-transfer schemas, separate from domain and persistence models."""

from rag_kb.domain import ErrorCode
from rag_kb.schemas.common import (
    CursorPage,
    CursorPayload,
    FieldViolation,
    PaginationQuery,
    ProblemDetails,
)
from rag_kb.schemas.chat import (
    AnswerPolicyOverrides,
    ChatAnswerCompletedEvent,
    ChatCitationResponse,
    ChatMessagePage,
    ChatMessageResponse,
    ChatRetrievalRequest,
    ChatRunCreate,
    ChatRunErrorResponse,
    ChatRunFailedEvent,
    ChatRunResponse,
    ChatSessionCreate,
    ChatSessionPage,
    ChatSessionResponse,
    EffectiveAnswerPolicyResponse,
)
from rag_kb.schemas.documents import (
    DocumentDeleteResponse,
    DocumentPage,
    DocumentResponse,
    DocumentUploadResponse,
    DocumentVersionResponse,
)
from rag_kb.schemas.indexing import IndexingErrorResponse, IndexingJobResponse
from rag_kb.schemas.knowledge_bases import (
    KnowledgeBaseAnswerPolicyDefaults,
    KnowledgeBaseCreate,
    KnowledgeBasePage,
    KnowledgeBaseResponse,
    KnowledgeBaseUpdate,
    RetrievalDefaults,
)
from rag_kb.schemas.retrieval import (
    EvidencePackResponse,
    EvidenceResponse,
    RetrievalDebugResponse,
    RetrievalQueryPlanResponse,
    RetrievalQueryRequest,
)

__all__ = [
    "AnswerPolicyOverrides",
    "ChatAnswerCompletedEvent",
    "ChatCitationResponse",
    "ChatMessagePage",
    "ChatMessageResponse",
    "ChatRetrievalRequest",
    "ChatRunCreate",
    "ChatRunErrorResponse",
    "ChatRunFailedEvent",
    "ChatRunResponse",
    "ChatSessionCreate",
    "ChatSessionPage",
    "ChatSessionResponse",
    "CursorPage",
    "CursorPayload",
    "DocumentDeleteResponse",
    "DocumentPage",
    "DocumentResponse",
    "DocumentUploadResponse",
    "DocumentVersionResponse",
    "IndexingErrorResponse",
    "IndexingJobResponse",
    "ErrorCode",
    "EffectiveAnswerPolicyResponse",
    "FieldViolation",
    "KnowledgeBaseCreate",
    "KnowledgeBaseAnswerPolicyDefaults",
    "KnowledgeBasePage",
    "KnowledgeBaseResponse",
    "KnowledgeBaseUpdate",
    "PaginationQuery",
    "ProblemDetails",
    "RetrievalDefaults",
    "EvidencePackResponse",
    "EvidenceResponse",
    "RetrievalDebugResponse",
    "RetrievalQueryPlanResponse",
    "RetrievalQueryRequest",
]
