"""Stable public error identifiers independent of HTTP rendering."""

from enum import StrEnum


class ErrorCode(StrEnum):
    REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED"
    INVALID_CURSOR = "INVALID_CURSOR"
    INVALID_IDEMPOTENCY_KEY = "INVALID_IDEMPOTENCY_KEY"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    CAPABILITY_NOT_ENABLED = "CAPABILITY_NOT_ENABLED"
    IDENTITY_OVERRIDE_NOT_ALLOWED = "IDENTITY_OVERRIDE_NOT_ALLOWED"
    ACCESS_DENIED = "ACCESS_DENIED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
