import type {
  ChatRun,
  ChatSession,
  DocumentRecord,
  DocumentUpload,
  EvidencePack,
  IndexingJob,
  KnowledgeBase,
} from "../api/types";

export const ids = {
  kb: "00000000-0000-4000-8000-000000000001",
  revision: "00000000-0000-4000-8000-000000000002",
  space: "00000000-0000-4000-8000-000000000003",
  document: "00000000-0000-4000-8000-000000000004",
  version: "00000000-0000-4000-8000-000000000005",
  indexedVersion: "00000000-0000-4000-8000-000000000006",
  job: "00000000-0000-4000-8000-000000000007",
  sourceChange: "00000000-0000-4000-8000-000000000008",
  session: "00000000-0000-4000-8000-000000000009",
  run: "00000000-0000-4000-8000-000000000010",
  userMessage: "00000000-0000-4000-8000-000000000011",
  assistantMessage: "00000000-0000-4000-8000-000000000012",
  chunk: "00000000-0000-4000-8000-000000000013",
  workspace: "00000000-0000-4000-8000-000000000014",
};

export const timestamp = "2026-07-15T08:00:00Z";

export const knowledgeBase: KnowledgeBase = {
  id: ids.kb,
  name: "Test knowledge",
  source_change_seq: 1,
  active_index_revision_id: ids.revision,
  embedding_space_id: ids.space,
  retrieval_defaults: { strategy: "exact_vector", top_k: 10 },
  answer_policy_defaults: {
    answer_style: "concise",
    insufficiency_policy: "refuse",
  },
  provisioned_at: timestamp,
  created_at: timestamp,
  updated_at: timestamp,
};

export const documentRecord: DocumentRecord = {
  id: ids.document,
  kb_id: ids.kb,
  display_name: "guide.md",
  current_version: {
    id: ids.version,
    version_number: 1,
    source_status: "available",
    checksum_sha256: "a".repeat(64),
    original_filename: "guide.md",
    media_type: "text/markdown",
    size_bytes: 24,
    created_at: timestamp,
  },
  deleted_at: null,
  created_at: timestamp,
  updated_at: timestamp,
};

export const documentUpload: DocumentUpload = {
  document: documentRecord,
  document_version_id: ids.version,
  source_change_id: ids.sourceChange,
  source_change_seq: 1,
  indexed_document_version_id: ids.indexedVersion,
  index_revision_id: ids.revision,
  job_id: ids.job,
  job_status: "queued",
};

export const failedJob: IndexingJob = {
  job_id: ids.job,
  kb_id: ids.kb,
  document_id: ids.document,
  document_version_id: ids.version,
  indexed_document_version_id: ids.indexedVersion,
  index_revision_id: ids.revision,
  status: "failed",
  phase: "embedding",
  attempt: 3,
  build_status: "failed",
  serving_status: "candidate",
  claimed_at: timestamp,
  heartbeat_at: timestamp,
  next_attempt_at: null,
  error: { code: "EMBEDDING_PROVIDER_UNAVAILABLE", detail: { phase: "embedding" } },
  can_retry: true,
  created_at: timestamp,
  updated_at: timestamp,
};

export const chatSession: ChatSession = {
  id: ids.session,
  knowledge_base_id: ids.kb,
  title: "Test session",
  created_at: timestamp,
  updated_at: timestamp,
};

export const completedRun: ChatRun = {
  run_id: ids.run,
  knowledge_base_id: ids.kb,
  session_id: ids.session,
  user_message_id: ids.userMessage,
  assistant_message_id: ids.assistantMessage,
  index_revision_id: ids.revision,
  status: "completed",
  assistant_status: "completed",
  answer: "The retained evidence supports this answer [1].",
  citations: [{
    ordinal: 0,
    index_chunk_id: ids.chunk,
    document_id: ids.document,
    document_version_id: ids.version,
    quoted_text: "Retained evidence text.",
    source_location: { line_start: 1, line_end: 2 },
    score: 0.92,
  }],
  status_url: `/api/v1/chat/runs/${ids.run}`,
  events_url: `/api/v1/chat/runs/${ids.run}/events`,
  effective_answer_policy: {
    grounding_policy: "evidence_only",
    answer_style: "concise",
    insufficiency_policy: "refuse",
    citation_required: true,
    citation_granularity: "claim_level",
    answer_task: "answer",
    policy_version: "p1",
  },
  retrieval: { strategy: "exact_vector", top_k: 10, rerank: false },
  attempt: 1,
  error: null,
  usage: { total_tokens: 42 },
  timing: { total_ms: 1200 },
  created_at: timestamp,
  updated_at: timestamp,
  completed_at: timestamp,
};

export const evidencePack: EvidencePack = {
  knowledge_base_id: ids.kb,
  index_revision_id: ids.revision,
  strategy: "exact_vector",
  evidence: [{
    rank: 1,
    index_chunk_id: ids.chunk,
    indexed_document_version_id: ids.indexedVersion,
    document_id: ids.document,
    document_version_id: ids.version,
    index_revision_id: ids.revision,
    ordinal: 0,
    text: "First serving evidence.",
    source_location: { line_start: 1 },
    hierarchy: { heading: "Overview" },
    source_metadata: { filename: "guide.md" },
    score: 0.93,
    score_kind: "cosine_similarity",
  }, {
    rank: 2,
    index_chunk_id: "00000000-0000-4000-8000-000000000099",
    indexed_document_version_id: ids.indexedVersion,
    document_id: ids.document,
    document_version_id: ids.version,
    index_revision_id: ids.revision,
    ordinal: 1,
    text: "Second serving evidence.",
    source_location: { line_start: 3 },
    hierarchy: {},
    source_metadata: {},
    score: 0.81,
    score_kind: "cosine_similarity",
  }],
  debug: {
    query_plan: {
      workspace_id: ids.workspace,
      knowledge_base_id: ids.kb,
      strategy: "exact_vector",
      top_k: 10,
      revision_selector: "active",
      current_document_version_only: true,
      build_status: "ready",
      serving_status: "serving",
      distance_metric: "cosine",
      candidate_count: null,
      ef_search: null,
      iterative_scan: "disabled",
      rerank: false,
    },
    resolved_active_revision_id: ids.revision,
    result_count: 2,
  },
};
